name: CD

on:
  push:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Build Artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .next   # Extract build output into .next directory

      - name: Show downloaded build
        run: ls -R .next

      - name: Build Docker Image
        run: |
          docker build -t gym-schedule-app:latest .

      - name: Save Docker Image as TAR
        run: |
          docker save gym-schedule-app:latest -o gym-schedule-app.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: gym-schedule-app.tar
